name = "evo2"
main = "dist/index.js"
compatibility_date = "2025-03-24"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./dist/public"

[build.upload]
format = "service-worker"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
